apiVersion: apps/v1
kind: Deployment
metadata:
  name: gx-compliance-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gx-compliance-server
  template:
    metadata:
      labels:
        app: gx-compliance-server
    spec:
      containers:
        - env:
            - name: PORT
              value: '3000'
          image: registry.gitlab.com/gaia-x/lab/compliance/gx-compliance:main
          name: gx-compliance-server
          ports:
            - containerPort: 3000
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: gx-compliance-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: gx-compliance-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gx-compliance-server
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - compliance.lab.gaia-x.eu
      secretName: gx-compliance-server-tls-secret
  rules:
    - host: compliance.lab.gaia-x.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gx-compliance-server
                port:
                  number: 80
