apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-description-signing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-description-signing-api
  template:
    metadata:
      labels:
        app: self-description-signing-api
    spec:
      containers:
        - env:
            - name: PORT
              value: '3000'
          image: ghcr.io/deltadao/self-description-signing-api:main
          name: self-description-signing-api
          ports:
            - containerPort: 3000
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: self-description-signing-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: self-description-signing-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: self-description-signing-api
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - signing-demo.delta-dao.com
      secretName: self-description-signing-api-tls-secret
  rules:
    - host: signing-demo.delta-dao.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: self-description-signing-api
                port:
                  number: 80
